### ISSUE TITLE
Parameter Issue

### ISSUE THREAD

**Issue by MohammedQallaf** [yazinsai/credimax-bahrain#1]
Dear , 

i Have two points : 
1-you need to modify the parameter in Config "script-out" to "return_url"
2- you need to make the secure Hash Changeable  upon Merchant ID . 

Regards

**Comment by yazinsai** [comment]
Gosh, it's been a while since I touched this script. 

Good points -- do you want to send in a PR?

**Comment by MohammedQallaf** [comment]
Yes I would like send  . 

Also , I have  simple request  , 

Do you have a documentation for BENEFITS integration in Bahrain .? or the Code it's self ?

**Comment by BuAlaa** [comment]
Hi 

Do you have working PHP example for Benefit ?

**Comment by yazinsai** [comment]
@BuAlaa  I do, it's hosted here: https://github.com/yazinsai/e24PaymentPipe-php

**Comment by yazinsai** [comment]
@MohammedQallaf I do have it somewhere, but it's a nightmare to navigate. Found it on Google: http://www.alamal-hospital.org/arabic/upload/library/a3a.pdf

**Comment by BuAlaa** [comment]
@yazinsai very thanks for your kind reply

**Comment by BuAlaa** [comment]
@yazinsai  do you have an implementation for WP woo-commerce  for the same?

**Comment by yazinsai** [comment]
@BuAlaa no I do not :) You can check out my project, [White](https://whitepayments.com/). We've got a [number of integrations](https://whitepayments.com/docs/integrations/), including WooCommerce.

Support for Debit Cards in Bahrain is in testing, but you can [sign up](https://whitepayments.com/global) to get notified when it's up.

**Comment by BuAlaa** [comment]
Hi; 

I have downloaded the 

 https://github.com/yazinsai/e24PaymentPipe-php

but not have an example for error and approve  page, it is directing to bank page but seems not returning back any code, 

would you please advise 
 
thanks

**Comment by yazinsai** [comment]
Did you pass in the correct `return_url` using `setResponseURL`?

**Comment by jd919294** [comment]
$CONFIG['return_url'] is not define in _config.php file

**Comment by jasperf** [comment]
@yazinsai You need to renew your SSL certificate for the White site I saw. But I guess you are more focussed at work at Payfort nowadays :) .

**Comment by yazinsai** [comment]
Nah, left Payfort ages ago :)

On October 15, 2017 1:57:07 AM EDT, Jasper Frumau <notifications@github.com> wrote:
>@yazinsai You need to renew your SSL certificate for the White site I
>saw. But I guess you are more focussed at work at Payfort nowadays :) .
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/yazinsai/credimax-bahrain/issues/1#issuecomment-336688629

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
