### ISSUE TITLE
having problem

### ISSUE THREAD

**Issue by waqasfrozen** [yazinsai/credimax-bahrain#2]
Hey Sir i am facing issue in this code can you please guide me how to create a sandbox id for credimax?

**Comment by alfredrumss** [comment]
hi, could you fix the issue? did you make the integration?

**Comment by jasperf** [comment]
@waqasfrozen Did you manage to get a sandbox ID? Does it require setting up a merchant account or can you just use sandbox API details?

**Comment by yazinsai** [comment]
You'd have to get that from Credimax
